/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.grudgeborne;

import javax.swing.JFrame;

import dev.grudgeborne.view.GamePanel;

public class Game {
  public static void main(String[] args) {
    JFrame frame = new JFrame("Grudge Born");

    GamePanel gamePanel = new GamePanel();
    frame.add(gamePanel);
    frame.pack();

    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setLocationRelativeTo(null);
    frame.setResizable(false);
    frame.setVisible(true);

    gamePanel.startGameThread();
  }
}
